name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test application startup
      run: |
        # Test that the application can start
        timeout 10s uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 5
        curl -f http://localhost:8000/ || exit 1
        
  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t calendar-link-generator .
      
    - name: Test Docker container
      run: |
        # Run container in background
        docker run -d -p 8000:8000 --name test-container calendar-link-generator
        
        # Wait for container to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8000/ || exit 1
        
        # Test API endpoint
        curl -X POST http://localhost:8000/generate-calendar-link \
          -H "Content-Type: application/json" \
          -d '{"event_text": "Test Meeting\nApril 30, 2024 2:00 PM EST"}' || exit 1
          
        # Clean up
        docker stop test-container
        docker rm test-container